"""add clustering result tables

Revision ID: 0004_clustering_tables
Revises: 0003_reorder_patent_cols
Create Date: 2026-07-14
"""
from __future__ import annotations

from alembic import op

revision = "0004_clustering_tables"
down_revision = "0003_reorder_patent_cols"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS core_layer.patent_embeddings (
            embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            core_patent_id BIGINT,
            patent_number TEXT NOT NULL,
            patent_number_type TEXT NOT NULL,
            "授權公告號" TEXT,
            "審查的公告號" TEXT,
            "未審查的公開號" TEXT,
            "申請號" TEXT,
            source_field TEXT NOT NULL,
            text_cleaning_version TEXT NOT NULL,
            raw_text_hash TEXT NOT NULL,
            model_text_hash TEXT NOT NULL,
            embedding_model TEXT NOT NULL,
            tokenizer_name TEXT,
            max_seq_length INTEGER NOT NULL,
            vector_dim INTEGER NOT NULL,
            embedding_vector VECTOR(768) NOT NULL,
            vector_hash TEXT,
            chunk_count INTEGER NOT NULL DEFAULT 1,
            chunk_token_counts_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            chunk_weights_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            aggregation_method TEXT NOT NULL DEFAULT 'weighted_mean',
            preprocessing_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            model_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT patent_embeddings_core_patent_id_fkey
                FOREIGN KEY (core_patent_id)
                REFERENCES core_layer.patents(id)
                ON DELETE SET NULL,
            CONSTRAINT patent_embeddings_patent_number_type_check
                CHECK (patent_number_type = ANY (ARRAY[
                    'grant_publication_number'::text,
                    'examined_publication_number'::text,
                    'unexamined_publication_number'::text,
                    'application_number'::text
                ])),
            CONSTRAINT patent_embeddings_source_field_check
                CHECK (source_field = ANY (ARRAY['wips_independent_claims'::text, 'effect_summary'::text])),
            CONSTRAINT patent_embeddings_vector_dim_check CHECK (vector_dim > 0),
            CONSTRAINT patent_embeddings_chunk_count_check CHECK (chunk_count >= 1),
            CONSTRAINT patent_embeddings_aggregation_method_check
                CHECK (aggregation_method = ANY (ARRAY['weighted_mean'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app_layer.workspaces (
            workspace_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_name TEXT NOT NULL,
            description TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            filter_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            archived_at TIMESTAMPTZ,
            CONSTRAINT workspaces_status_check
                CHECK (status = ANY (ARRAY['active'::text, 'archived'::text, 'disabled'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app_layer.workspace_patents (
            workspace_id BIGINT NOT NULL,
            patent_id BIGINT NOT NULL,
            source_type TEXT NOT NULL DEFAULT 'manual',
            source_ref TEXT,
            added_by TEXT,
            added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (workspace_id, patent_id),
            CONSTRAINT workspace_patents_workspace_id_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE CASCADE,
            CONSTRAINT workspace_patents_patent_id_fkey
                FOREIGN KEY (patent_id)
                REFERENCES core_layer.patents(id)
                ON DELETE CASCADE,
            CONSTRAINT workspace_patents_source_type_check
                CHECK (source_type = ANY (ARRAY['manual'::text, 'import'::text, 'filter'::text, 'incremental_import'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_model_profiles (
            profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_name TEXT NOT NULL,
            source_field TEXT NOT NULL,
            embedding_model TEXT NOT NULL,
            tokenizer_name TEXT,
            max_seq_length INTEGER,
            text_cleaning_version TEXT NOT NULL DEFAULT 'patent_text_clean_v1',
            pipeline_version TEXT NOT NULL,
            parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            quality_gate_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            superseded_at TIMESTAMPTZ,
            CONSTRAINT topic_model_profiles_source_field_check
                CHECK (source_field = ANY (ARRAY['wips_independent_claims'::text, 'effect_summary'::text])),
            CONSTRAINT topic_model_profiles_status_check
                CHECK (status = ANY (ARRAY['active'::text, 'superseded'::text, 'disabled'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_runs (
            run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id BIGINT NOT NULL,
            scope_type TEXT NOT NULL,
            workspace_id BIGINT,
            analysis_id BIGINT,
            source_field TEXT NOT NULL,
            run_mode TEXT NOT NULL DEFAULT 'full',
            previous_run_id BIGINT,
            base_run_id BIGINT,
            status TEXT NOT NULL DEFAULT 'pending',
            selected_patent_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            new_patent_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            input_doc_count INTEGER NOT NULL DEFAULT 0,
            new_doc_count INTEGER NOT NULL DEFAULT 0,
            reused_assignment_count INTEGER NOT NULL DEFAULT 0,
            accepted_topic_count INTEGER NOT NULL DEFAULT 0,
            parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            incremental_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            selected_candidate_id TEXT,
            error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at TIMESTAMPTZ,
            CONSTRAINT topic_runs_profile_id_fkey
                FOREIGN KEY (profile_id)
                REFERENCES derived_layer.topic_model_profiles(profile_id)
                ON DELETE RESTRICT,
            CONSTRAINT topic_runs_analysis_id_fkey
                FOREIGN KEY (analysis_id)
                REFERENCES app_layer.analysis_runs(analysis_id)
                ON DELETE RESTRICT,
            CONSTRAINT topic_runs_workspace_id_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE RESTRICT,
            CONSTRAINT topic_runs_previous_run_id_fkey
                FOREIGN KEY (previous_run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE SET NULL,
            CONSTRAINT topic_runs_base_run_id_fkey
                FOREIGN KEY (base_run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE SET NULL,
            CONSTRAINT topic_runs_scope_type_check
                CHECK (scope_type = ANY (ARRAY['global'::text, 'workspace'::text])),
            CONSTRAINT topic_runs_workspace_scope_check
                CHECK (
                    (scope_type = 'global' AND workspace_id IS NULL)
                    OR (scope_type = 'workspace' AND workspace_id IS NOT NULL)
                ),
            CONSTRAINT topic_runs_source_field_check
                CHECK (source_field = ANY (ARRAY['wips_independent_claims'::text, 'effect_summary'::text])),
            CONSTRAINT topic_runs_run_mode_check
                CHECK (run_mode = ANY (ARRAY['full'::text, 'incremental'::text, 'recalibration'::text, 'calibrate'::text])),
            CONSTRAINT topic_runs_status_check
                CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'needs_review'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_model_artifacts (
            artifact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id BIGINT NOT NULL,
            run_id BIGINT NOT NULL,
            artifact_type TEXT NOT NULL,
            file_path TEXT NOT NULL,
            file_hash TEXT,
            parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topic_model_artifacts_profile_id_fkey
                FOREIGN KEY (profile_id)
                REFERENCES derived_layer.topic_model_profiles(profile_id)
                ON DELETE RESTRICT,
            CONSTRAINT topic_model_artifacts_run_id_fkey
                FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_model_artifacts_artifact_type_check
                CHECK (artifact_type = ANY (ARRAY[
                    'bertopic_model'::text,
                    'embedding_cache'::text,
                    'kmeans_model'::text,
                    'vectorizer'::text,
                    'ctfidf'::text,
                    'tokenizer_snapshot'::text
                ]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topics (
            topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            parent_topic_id BIGINT,
            topic_code TEXT NOT NULL,
            depth INTEGER NOT NULL,
            topic_path TEXT NOT NULL,
            is_leaf_topic BOOLEAN NOT NULL DEFAULT true,
            doc_count INTEGER NOT NULL DEFAULT 0,
            doc_ratio DOUBLE PRECISION,
            coherence DOUBLE PRECISION,
            diversity DOUBLE PRECISION,
            balance DOUBLE PRECISION,
            keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            representative_patent_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            status TEXT NOT NULL DEFAULT 'accepted',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topics_run_id_fkey
                FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE CASCADE,
            CONSTRAINT topics_parent_topic_id_fkey
                FOREIGN KEY (parent_topic_id)
                REFERENCES derived_layer.topics(topic_id)
                ON DELETE CASCADE,
            CONSTRAINT topics_depth_check CHECK (depth >= 1),
            CONSTRAINT topics_doc_count_check CHECK (doc_count >= 0),
            CONSTRAINT topics_status_check
                CHECK (status = ANY (ARRAY['accepted'::text, 'needs_review'::text, 'rejected'::text, 'superseded'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_quality_metrics (
            metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            parent_topic_id BIGINT,
            candidate_id TEXT NOT NULL,
            candidate_k INTEGER NOT NULL,
            coherence DOUBLE PRECISION,
            diversity DOUBLE PRECISION,
            balance DOUBLE PRECISION,
            max_topic_ratio DOUBLE PRECISION,
            small_topic_ratio DOUBLE PRECISION,
            score DOUBLE PRECISION,
            passed_gate BOOLEAN NOT NULL DEFAULT false,
            candidate_type TEXT NOT NULL DEFAULT 'raw_candidate',
            candidate_explanation TEXT,
            metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topic_quality_metrics_run_id_fkey
                FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_quality_metrics_parent_topic_id_fkey
                FOREIGN KEY (parent_topic_id)
                REFERENCES derived_layer.topics(topic_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_quality_metrics_candidate_k_check CHECK (candidate_k > 0),
            CONSTRAINT topic_quality_metrics_candidate_type_check
                CHECK (candidate_type = ANY (ARRAY['conservative'::text, 'balanced'::text, 'detailed'::text, 'raw_candidate'::text]))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_candidate_selections (
            selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            selected_candidate_id TEXT NOT NULL,
            selected_by TEXT,
            selected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            selection_reason TEXT,
            candidate_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT topic_candidate_selections_run_id_fkey
                FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE CASCADE
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_assignments (
            assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            topic_id BIGINT NOT NULL,
            patent_id BIGINT NOT NULL,
            source_field TEXT NOT NULL,
            assignment_depth INTEGER NOT NULL,
            is_leaf_assignment BOOLEAN NOT NULL DEFAULT true,
            distance_to_centroid DOUBLE PRECISION,
            confidence_score DOUBLE PRECISION,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topic_assignments_run_id_fkey
                FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_assignments_topic_id_fkey
                FOREIGN KEY (topic_id)
                REFERENCES derived_layer.topics(topic_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_assignments_patent_id_fkey
                FOREIGN KEY (patent_id)
                REFERENCES core_layer.patents(id)
                ON DELETE CASCADE,
            CONSTRAINT topic_assignments_source_field_check
                CHECK (source_field = ANY (ARRAY['wips_independent_claims'::text, 'effect_summary'::text])),
            CONSTRAINT topic_assignments_assignment_depth_check CHECK (assignment_depth >= 1),
            CONSTRAINT topic_assignments_confidence_score_check
                CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
        );
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.topic_labels (
            label_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            topic_id BIGINT NOT NULL,
            label_type TEXT NOT NULL,
            label TEXT NOT NULL,
            summary TEXT,
            llm_model TEXT,
            prompt_version TEXT,
            confidence DOUBLE PRECISION,
            rationale_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_by TEXT,
            CONSTRAINT topic_labels_topic_id_fkey
                FOREIGN KEY (topic_id)
                REFERENCES derived_layer.topics(topic_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_labels_label_type_check
                CHECK (label_type = ANY (ARRAY['llm'::text, 'manual'::text])),
            CONSTRAINT topic_labels_confidence_check
                CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
        );
        """
    )

    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_workspaces_name ON app_layer.workspaces(workspace_name);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_workspaces_status ON app_layer.workspaces(status);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_workspace_patents_patent_id ON app_layer.workspace_patents(patent_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_workspace_patents_source_type ON app_layer.workspace_patents(source_type);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_patent_embeddings_core_patent_id ON core_layer.patent_embeddings(core_patent_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_patent_embeddings_patent_number ON core_layer.patent_embeddings(patent_number);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_patent_embeddings_source_field ON core_layer.patent_embeddings(source_field);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_patent_embeddings_model_hash ON core_layer.patent_embeddings(embedding_model, model_text_hash);")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_patent_embeddings_identity ON core_layer.patent_embeddings(patent_number_type, patent_number, source_field, embedding_model, model_text_hash);")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_topic_model_profiles_name ON derived_layer.topic_model_profiles(profile_name);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_model_profiles_source_field ON derived_layer.topic_model_profiles(source_field);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_model_profiles_status ON derived_layer.topic_model_profiles(status);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_profile_id ON derived_layer.topic_runs(profile_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_scope ON derived_layer.topic_runs(scope_type, workspace_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_source_field ON derived_layer.topic_runs(source_field);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_status ON derived_layer.topic_runs(status);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_previous_run_id ON derived_layer.topic_runs(previous_run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_runs_base_run_id ON derived_layer.topic_runs(base_run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_model_artifacts_profile_id ON derived_layer.topic_model_artifacts(profile_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_model_artifacts_run_id ON derived_layer.topic_model_artifacts(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_model_artifacts_type ON derived_layer.topic_model_artifacts(artifact_type);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topics_run_id ON derived_layer.topics(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topics_parent_topic_id ON derived_layer.topics(parent_topic_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topics_run_depth ON derived_layer.topics(run_id, depth);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topics_leaf_status ON derived_layer.topics(run_id, is_leaf_topic, status);")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_topics_run_topic_code ON derived_layer.topics(run_id, topic_code);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_quality_metrics_run_id ON derived_layer.topic_quality_metrics(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_quality_metrics_parent_topic_id ON derived_layer.topic_quality_metrics(parent_topic_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_quality_metrics_candidate_type ON derived_layer.topic_quality_metrics(run_id, candidate_type);")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_topic_quality_metrics_run_candidate ON derived_layer.topic_quality_metrics(run_id, candidate_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_candidate_selections_run_id ON derived_layer.topic_candidate_selections(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_assignments_run_id ON derived_layer.topic_assignments(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_assignments_topic_id ON derived_layer.topic_assignments(topic_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_assignments_patent_id ON derived_layer.topic_assignments(patent_id);")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_topic_assignments_leaf ON derived_layer.topic_assignments(run_id, patent_id, source_field, assignment_depth, is_leaf_assignment);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_labels_topic_id ON derived_layer.topic_labels(topic_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_topic_labels_label_type ON derived_layer.topic_labels(label_type);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_labels CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_assignments CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_candidate_selections CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_quality_metrics CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topics CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_model_artifacts CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_runs CASCADE;")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_model_profiles CASCADE;")
    op.execute("DROP TABLE IF EXISTS app_layer.workspace_patents CASCADE;")
    op.execute("DROP TABLE IF EXISTS app_layer.workspaces CASCADE;")
    op.execute("DROP TABLE IF EXISTS core_layer.patent_embeddings CASCADE;")
