"""reorder simplified patent embedding columns

Revision ID: 0007_reorder_embeddings
Revises: 0006_simplify_topics
Create Date: 2026-07-15
"""
from __future__ import annotations

from alembic import op


revision = "0007_reorder_embeddings"
down_revision = "0006_simplify_topics"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """重建 embedding 表以固定 DBeaver 可讀欄位順序，並逐向量驗證內容。"""
    op.execute(
        """
        CREATE TABLE core_layer.patent_embeddings_reordered (
            embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patent_id BIGINT NOT NULL,
            patent_number TEXT NOT NULL,
            patent_number_type TEXT NOT NULL,
            source_field TEXT NOT NULL,
            preprocessing_version TEXT NOT NULL,
            text_hash TEXT NOT NULL,
            embedding_model TEXT NOT NULL,
            model_version TEXT NOT NULL,
            embedding_vector VECTOR(768) NOT NULL,
            chunk_count INTEGER NOT NULL DEFAULT 1,
            aggregation_method TEXT NOT NULL DEFAULT 'weighted_mean',
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT patent_embeddings_reordered_patent_id_fkey
                FOREIGN KEY (patent_id)
                REFERENCES core_layer.patents(id)
                ON DELETE CASCADE,
            CONSTRAINT patent_embeddings_reordered_patent_number_type_check
                CHECK (patent_number_type = ANY (ARRAY[
                    'grant_publication_number'::text,
                    'examined_publication_number'::text,
                    'unexamined_publication_number'::text,
                    'application_number'::text
                ])),
            CONSTRAINT patent_embeddings_reordered_source_field_check
                CHECK (source_field = ANY (ARRAY[
                    'wips_independent_claims'::text,
                    'effect_summary'::text
                ])),
            CONSTRAINT patent_embeddings_reordered_chunk_count_check CHECK (chunk_count >= 1),
            CONSTRAINT patent_embeddings_reordered_aggregation_method_check
                CHECK (aggregation_method = 'weighted_mean')
        );

        INSERT INTO core_layer.patent_embeddings_reordered (
            embedding_id,
            patent_id,
            patent_number,
            patent_number_type,
            source_field,
            preprocessing_version,
            text_hash,
            embedding_model,
            model_version,
            embedding_vector,
            chunk_count,
            aggregation_method,
            metadata_json,
            created_at
        )
        SELECT
            embedding_id,
            patent_id,
            patent_number,
            patent_number_type,
            source_field,
            preprocessing_version,
            text_hash,
            embedding_model,
            model_version,
            embedding_vector,
            chunk_count,
            aggregation_method,
            metadata_json,
            created_at
        FROM core_layer.patent_embeddings
        ORDER BY embedding_id;
        """
    )
    op.execute(
        """
        DO $$
        DECLARE
            old_count BIGINT;
            new_count BIGINT;
            old_fingerprint TEXT;
            new_fingerprint TEXT;
        BEGIN
            SELECT
                count(*),
                md5(string_agg(
                    embedding_id::text || ':' || patent_id::text || ':' || embedding_vector::text,
                    '|' ORDER BY embedding_id
                ))
            INTO old_count, old_fingerprint
            FROM core_layer.patent_embeddings;

            SELECT
                count(*),
                md5(string_agg(
                    embedding_id::text || ':' || patent_id::text || ':' || embedding_vector::text,
                    '|' ORDER BY embedding_id
                ))
            INTO new_count, new_fingerprint
            FROM core_layer.patent_embeddings_reordered;

            IF old_count <> new_count OR old_fingerprint IS DISTINCT FROM new_fingerprint THEN
                RAISE EXCEPTION
                    'embedding reorder validation failed: old=%/% new=%/%',
                    old_count, old_fingerprint, new_count, new_fingerprint;
            END IF;
        END $$;
        """
    )
    op.execute("DROP TABLE core_layer.patent_embeddings CASCADE;")
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings_reordered "
        "RENAME TO patent_embeddings;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_pkey TO patent_embeddings_pkey;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_patent_id_fkey "
        "TO patent_embeddings_patent_id_fkey;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_patent_number_type_check "
        "TO patent_embeddings_patent_number_type_check;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_source_field_check "
        "TO patent_embeddings_source_field_check;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_chunk_count_check "
        "TO patent_embeddings_chunk_count_check;"
    )
    op.execute(
        "ALTER TABLE core_layer.patent_embeddings "
        "RENAME CONSTRAINT patent_embeddings_reordered_aggregation_method_check "
        "TO patent_embeddings_aggregation_method_check;"
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('core_layer.patent_embeddings', 'embedding_id'),
            COALESCE((SELECT max(embedding_id) FROM core_layer.patent_embeddings), 1),
            EXISTS (SELECT 1 FROM core_layer.patent_embeddings)
        );
        """
    )
    op.execute(
        "CREATE INDEX idx_patent_embeddings_patent_id "
        "ON core_layer.patent_embeddings(patent_id);"
    )
    op.execute(
        "CREATE INDEX idx_patent_embeddings_patent_number "
        "ON core_layer.patent_embeddings(patent_number);"
    )
    op.execute(
        "CREATE INDEX idx_patent_embeddings_source_field "
        "ON core_layer.patent_embeddings(source_field);"
    )
    op.execute(
        "CREATE INDEX idx_patent_embeddings_lookup "
        "ON core_layer.patent_embeddings(source_field, embedding_model, model_version, text_hash);"
    )
    op.execute(
        """
        CREATE UNIQUE INDEX ux_patent_embeddings_identity
        ON core_layer.patent_embeddings(
            patent_id,
            source_field,
            embedding_model,
            model_version,
            preprocessing_version,
            text_hash,
            aggregation_method
        );
        """
    )


def downgrade() -> None:
    """欄位重排不改語意；保留現況，避免為視覺順序再次重建大型向量表。"""
    raise RuntimeError(
        "0007 only changes physical column order; restore the pre-0007 backup if downgrade is required"
    )
