"""split embedding stores and persist workspace topic state

Revision ID: 0010_workspace_topic_engine
Revises: 0009_citation_report_cols
Create Date: 2026-07-15
"""
from __future__ import annotations

from alembic import op


revision = "0010_workspace_topic_engine"
down_revision = "0009_citation_report_cols"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """拆分雙向量表，並將主題改為 workspace 可持續更新的永久實體。"""
    _move_effect_summary_to_patents()
    _split_embedding_tables()
    _replace_topic_state_tables()


def downgrade() -> None:
    """阻止會遺失人工合併關係的降版，需由完整備份復原。"""
    raise RuntimeError(
        "0010 splits embeddings and changes topic identity semantics; "
        "restore the pre-0010 database backup instead"
    )


def _move_effect_summary_to_patents() -> None:
    """將既有 WIPS 功效摘要原值搬入專利核心表，完成後移除舊欄。"""
    op.execute(
        'ALTER TABLE core_layer.patents '
        'ADD COLUMN "效果 摘要[US,EP,PCT,JP,KR,CN,TW]" TEXT;'
    )
    op.execute(
        """
        UPDATE core_layer.patents p
        SET "效果 摘要[US,EP,PCT,JP,KR,CN,TW]" = pa."效果 摘要[US,EP,PCT,JP,KR,CN,TW]"
        FROM core_layer.patent_attributes pa
        WHERE pa.patent_id = p.id
          AND NULLIF(BTRIM(pa."效果 摘要[US,EP,PCT,JP,KR,CN,TW]"), '') IS NOT NULL;
        """
    )
    op.execute(
        'ALTER TABLE core_layer.patent_attributes '
        'DROP COLUMN "效果 摘要[US,EP,PCT,JP,KR,CN,TW]";'
    )


def _split_embedding_tables() -> None:
    """保留既有技術向量，建立欄位一致且來源明確的技術／功效向量表。"""
    for table_name in ("patent_technical_embeddings", "patent_effect_embeddings"):
        op.execute(
            f"""
            CREATE TABLE core_layer.{table_name} (
                embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                patent_id BIGINT NOT NULL,
                text_hash TEXT NOT NULL,
                embedding_model TEXT NOT NULL,
                model_version TEXT NOT NULL,
                preprocessing_version TEXT NOT NULL,
                embedding_vector VECTOR(768) NOT NULL,
                chunk_count INTEGER NOT NULL DEFAULT 1,
                metadata_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT {table_name}_patent_id_fkey
                    FOREIGN KEY (patent_id)
                    REFERENCES core_layer.patents(id)
                    ON DELETE CASCADE,
                CONSTRAINT {table_name}_chunk_count_check CHECK (chunk_count >= 1)
            );
            """
        )
        op.execute(
            f"""
            CREATE UNIQUE INDEX ux_{table_name}_identity
            ON core_layer.{table_name}(
                patent_id,
                text_hash,
                embedding_model,
                model_version,
                preprocessing_version
            );
            """
        )
        op.execute(
            f"CREATE INDEX idx_{table_name}_patent_id "
            f"ON core_layer.{table_name}(patent_id);"
        )

    # 0004-0009 產生的既有向量都是獨立項；原值搬移，不重新計算向量。
    op.execute(
        """
        INSERT INTO core_layer.patent_technical_embeddings (
            embedding_id,
            patent_id,
            text_hash,
            embedding_model,
            model_version,
            preprocessing_version,
            embedding_vector,
            chunk_count,
            metadata_json,
            created_at
        )
        SELECT
            embedding_id,
            patent_id,
            text_hash,
            embedding_model,
            model_version,
            preprocessing_version,
            embedding_vector,
            chunk_count,
            metadata_json || jsonb_build_object(
                'aggregation_method', aggregation_method,
                'legacy_source_field', source_field
            ),
            created_at
        FROM core_layer.patent_embeddings
        WHERE source_field = 'wips_independent_claims';
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('core_layer.patent_technical_embeddings', 'embedding_id'),
            GREATEST(
                COALESCE((SELECT max(embedding_id) FROM core_layer.patent_technical_embeddings), 1),
                1
            ),
            EXISTS (SELECT 1 FROM core_layer.patent_technical_embeddings)
        );
        """
    )
    op.execute("DROP TABLE core_layer.patent_embeddings;")


def _replace_topic_state_tables() -> None:
    """讓 topic ID 跨 full/incremental/merge run 穩定，並保留既有候選校正紀錄。"""
    # 舊版尚未正式寫入 topic；若其他環境已有值，先設計明確轉檔，避免猜測 model topic ID。
    op.execute(
        """
        DO $$
        DECLARE
            populated_rows BIGINT;
        BEGIN
            SELECT
                (SELECT count(*) FROM derived_layer.topics)
                + (SELECT count(*) FROM derived_layer.topic_assignments)
            INTO populated_rows;

            IF populated_rows > 0 THEN
                RAISE EXCEPTION
                    '0010 requires empty legacy topics and assignments; found % rows',
                    populated_rows;
            END IF;
        END $$;
        """
    )

    # topic_candidates 在舊 schema 以 (parent_topic_id, run_id) 參照 topics，
    # 必須先拆 FK，才能重建穩定 topic identity 表。
    op.execute("DROP INDEX IF EXISTS derived_layer.ux_topic_candidates_type;")
    op.execute("DROP INDEX IF EXISTS derived_layer.ux_topic_candidates_one_selected;")
    op.execute(
        "ALTER TABLE derived_layer.topic_candidates "
        "DROP CONSTRAINT IF EXISTS topic_candidates_parent_topic_run_fkey;"
    )
    op.execute("DROP TABLE derived_layer.topic_assignments;")
    op.execute("DROP TABLE derived_layer.topics;")

    op.execute("ALTER TABLE derived_layer.topic_candidates DROP COLUMN parent_topic_id;")
    op.execute(
        "CREATE UNIQUE INDEX ux_topic_candidates_type "
        "ON derived_layer.topic_candidates(run_id, candidate_type);"
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_topic_candidates_one_selected "
        "ON derived_layer.topic_candidates(run_id) WHERE is_selected;"
    )

    op.execute(
        "ALTER TABLE derived_layer.topic_runs "
        "DROP CONSTRAINT topic_runs_run_mode_check;"
    )
    op.execute(
        "ALTER TABLE derived_layer.topic_runs "
        "ADD CONSTRAINT topic_runs_run_mode_check "
        "CHECK (run_mode = ANY (ARRAY['full'::text, 'incremental'::text, 'merge'::text]));"
    )
    op.execute(
        "ALTER TABLE derived_layer.topic_runs "
        "ADD COLUMN artifact_version INTEGER NOT NULL DEFAULT 1, "
        "ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "ADD CONSTRAINT topic_runs_artifact_version_check CHECK (artifact_version >= 1);"
    )

    op.execute(
        """
        CREATE TABLE derived_layer.topics (
            topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id BIGINT NOT NULL,
            source_field TEXT NOT NULL,
            created_run_id BIGINT NOT NULL,
            topic_code TEXT NOT NULL,
            model_topic_ids INTEGER[] NOT NULL DEFAULT '{}'::integer[],
            topic_kind TEXT NOT NULL DEFAULT 'model',
            doc_count INTEGER NOT NULL DEFAULT 0,
            coherence DOUBLE PRECISION,
            diversity DOUBLE PRECISION,
            balance DOUBLE PRECISION,
            keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            representative_patent_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            label TEXT,
            summary TEXT,
            label_source TEXT,
            label_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            display_order INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active',
            merged_into_topic_id BIGINT,
            merged_by TEXT,
            merged_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topics_workspace_id_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE CASCADE,
            CONSTRAINT topics_created_run_id_fkey
                FOREIGN KEY (created_run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE RESTRICT,
            CONSTRAINT topics_merged_into_topic_id_fkey
                FOREIGN KEY (merged_into_topic_id)
                REFERENCES derived_layer.topics(topic_id)
                ON DELETE RESTRICT,
            CONSTRAINT topics_source_field_check
                CHECK (source_field = ANY (ARRAY[
                    'wips_independent_claims'::text,
                    'effect_summary'::text
                ])),
            CONSTRAINT topics_kind_check
                CHECK (topic_kind = ANY (ARRAY['model'::text, 'unclassified'::text, 'other'::text])),
            CONSTRAINT topics_status_check
                CHECK (status = ANY (ARRAY['active'::text, 'merged'::text])),
            CONSTRAINT topics_doc_count_check CHECK (doc_count >= 0),
            CONSTRAINT topics_display_order_check CHECK (display_order >= 0),
            CONSTRAINT topics_label_source_check
                CHECK (label_source IS NULL OR label_source = ANY (ARRAY['llm'::text, 'manual'::text, 'fallback'::text])),
            CONSTRAINT topics_merge_state_check CHECK (
                (status = 'active' AND merged_into_topic_id IS NULL AND merged_at IS NULL)
                OR
                (status = 'merged' AND merged_into_topic_id IS NOT NULL AND merged_at IS NOT NULL)
            ),
            CONSTRAINT topics_workspace_code_key UNIQUE (workspace_id, source_field, topic_code),
            CONSTRAINT topics_identity_scope_key UNIQUE (topic_id, workspace_id, source_field)
        );
        """
    )
    op.execute(
        "CREATE INDEX idx_topics_workspace_source_status "
        "ON derived_layer.topics(workspace_id, source_field, status, display_order);"
    )
    op.execute(
        "CREATE INDEX idx_topics_merged_into "
        "ON derived_layer.topics(merged_into_topic_id) WHERE merged_into_topic_id IS NOT NULL;"
    )

    op.execute(
        """
        CREATE TABLE derived_layer.topic_assignments (
            assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id BIGINT NOT NULL,
            source_field TEXT NOT NULL,
            patent_id BIGINT NOT NULL,
            topic_id BIGINT NOT NULL,
            assigned_run_id BIGINT NOT NULL,
            distance_to_centroid DOUBLE PRECISION,
            is_current BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT topic_assignments_workspace_id_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE CASCADE,
            CONSTRAINT topic_assignments_topic_scope_fkey
                FOREIGN KEY (topic_id, workspace_id, source_field)
                REFERENCES derived_layer.topics(topic_id, workspace_id, source_field)
                ON DELETE RESTRICT,
            CONSTRAINT topic_assignments_patent_id_fkey
                FOREIGN KEY (patent_id)
                REFERENCES core_layer.patents(id)
                ON DELETE CASCADE,
            CONSTRAINT topic_assignments_assigned_run_id_fkey
                FOREIGN KEY (assigned_run_id)
                REFERENCES derived_layer.topic_runs(run_id)
                ON DELETE RESTRICT,
            CONSTRAINT topic_assignments_source_field_check
                CHECK (source_field = ANY (ARRAY[
                    'wips_independent_claims'::text,
                    'effect_summary'::text
                ])),
            CONSTRAINT topic_assignments_distance_check
                CHECK (distance_to_centroid IS NULL OR distance_to_centroid >= 0)
        );
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_topic_assignments_current "
        "ON derived_layer.topic_assignments(workspace_id, source_field, patent_id) "
        "WHERE is_current;"
    )
    op.execute(
        "CREATE INDEX idx_topic_assignments_topic_current "
        "ON derived_layer.topic_assignments(topic_id, is_current);"
    )
    op.execute(
        "CREATE INDEX idx_topic_assignments_patent_id "
        "ON derived_layer.topic_assignments(patent_id);"
    )
