"""add app_layer.processing_jobs queue table

Revision ID: 0012_processing_jobs
Revises: 0011_unmerge_history
Create Date: 2026-07-17

第一版 backend／worker 的 Job queue（patent-backend-worker-plan.md 定案）：
PostgreSQL 單表兼任佇列、狀態與結果，不引入 Celery／Redis。合法 job_type
由 Python enum／API 驗證，DB 不設 job_type check（未來加工作類型免改 constraint）。
"""
from __future__ import annotations

from alembic import op


revision = "0012_processing_jobs"
down_revision = "0011_unmerge_history"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """建立 app_layer.processing_jobs 及狀態機 constraint 與領取用 index。"""
    op.execute(
        """
        CREATE TABLE app_layer.processing_jobs (
            job_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_type          TEXT NOT NULL,
            status            TEXT NOT NULL DEFAULT 'queued',
            workspace_id      BIGINT,
            payload_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
            result_json       JSONB,
            progress_percent  INTEGER NOT NULL DEFAULT 0,
            current_stage     TEXT NOT NULL DEFAULT 'queued',
            idempotency_key   TEXT,
            attempt_count     INTEGER NOT NULL DEFAULT 0,
            max_attempts      INTEGER NOT NULL DEFAULT 3,
            locked_by         TEXT,
            locked_at         TIMESTAMPTZ,
            heartbeat_at      TIMESTAMPTZ,
            error_message     TEXT,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            started_at        TIMESTAMPTZ,
            finished_at       TIMESTAMPTZ,
            CONSTRAINT processing_jobs_workspace_id_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE SET NULL,
            CONSTRAINT processing_jobs_status_check
                CHECK (status = ANY (ARRAY[
                    'queued'::text,
                    'running'::text,
                    'succeeded'::text,
                    'failed'::text,
                    'cancelled'::text
                ])),
            CONSTRAINT processing_jobs_progress_check
                CHECK (progress_percent BETWEEN 0 AND 100),
            CONSTRAINT processing_jobs_attempt_count_check
                CHECK (attempt_count >= 0),
            CONSTRAINT processing_jobs_max_attempts_check
                CHECK (max_attempts >= 1),
            CONSTRAINT processing_jobs_attempt_bound_check
                CHECK (attempt_count <= max_attempts)
        );
        """
    )

    # idempotency：同 key 只能有一筆工作；NULL 不受限（多數工作不帶 key）。
    op.execute(
        """
        CREATE UNIQUE INDEX ux_processing_jobs_idempotency
            ON app_layer.processing_jobs (idempotency_key)
            WHERE idempotency_key IS NOT NULL;
        """
    )
    # 佇列領取：只掃 queued，依 created_at, job_id 排序（FOR UPDATE SKIP LOCKED）。
    op.execute(
        """
        CREATE INDEX idx_processing_jobs_queue
            ON app_layer.processing_jobs (status, created_at, job_id)
            WHERE status = 'queued';
        """
    )
    # heartbeat 逾時回收：只掃 running 的心跳時間。
    op.execute(
        """
        CREATE INDEX idx_processing_jobs_running_heartbeat
            ON app_layer.processing_jobs (heartbeat_at)
            WHERE status = 'running';
        """
    )
    # 前端依 workspace 列出工作歷史（新到舊）。
    op.execute(
        """
        CREATE INDEX idx_processing_jobs_workspace_created
            ON app_layer.processing_jobs (workspace_id, created_at DESC);
        """
    )


def downgrade() -> None:
    """全新獨立表，無外部依賴，直接移除。"""
    op.execute("DROP TABLE app_layer.processing_jobs;")
