"""upgrade company alias table and add normalization task queue

Revision ID: 0013_company_alias_normalization
Revises: 0012_processing_jobs
Create Date: 2026-07-17

專利權人/公司正規化的 DB 端（decisions.md 2026-07-17 兩條定案）：
- DB 只有一張對照表 → 就地升級 derived_layer.company_aliases，不建第二張。
- alias_lookup_key 用 GENERATED STORED 欄，運算式與 refresh_report_patent_base
  比對別稱時完全相同（lower + 壓空白），DB 保證一致、免改 importer。
- 新增 app_layer.company_normalization_tasks 作為待補全任務清單（WIPS 查詢），
  與 processing_jobs 分開：它是給 Claude Code／MCP 的工作清單，非 worker job。
- 新增 derived_layer.v_unmapped_company_names，列出對照表未覆蓋的公司名，
  供「掃描未正規化公司」的 MCP 工具直接查。
原有專利的公司/申請人/專利權人/受讓人來源欄位值不動；報表透過對照表取正規化名。
"""
from __future__ import annotations

from alembic import op


revision = "0013_company_alias_normalization"
down_revision = "0012_processing_jobs"
branch_labels = None
depends_on = None


# 別稱正規化運算式：與 refresh_report_patent_base 對別稱的比對完全一致
# （lower + 連續空白壓成單一空白 + 去頭尾），確保 view/對照表/報表同口徑。
_NORMALIZE = r"lower(regexp_replace(btrim({col}), '\s+', ' ', 'g'))"


def upgrade() -> None:
    """升級 company_aliases、建任務表與未映射公司 view。"""
    # ── 2a. company_aliases 加欄（alias_lookup_key 為 generated，免回填）──
    op.execute(
        f"""
        ALTER TABLE derived_layer.company_aliases
            ADD COLUMN alias_lookup_key TEXT
                GENERATED ALWAYS AS ({_NORMALIZE.format(col='"別稱"')}) STORED,
            ADD COLUMN source_type TEXT NOT NULL DEFAULT 'excel_seed',
            ADD COLUMN review_status TEXT NOT NULL DEFAULT 'confirmed',
            ADD COLUMN wips_metadata_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
            ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            ADD CONSTRAINT company_aliases_source_type_check
                CHECK (source_type = ANY (ARRAY[
                    'excel_seed'::text, 'wips_lookup'::text, 'manual'::text])),
            ADD CONSTRAINT company_aliases_review_status_check
                CHECK (review_status = ANY (ARRAY[
                    'confirmed'::text, 'review_required'::text]));
        """
    )
    # 確認態的別稱不得指向兩家公司；review_required 可暫存歧義等人工裁決，不擋流程。
    op.execute(
        """
        CREATE UNIQUE INDEX ux_company_aliases_lookup_confirmed
            ON derived_layer.company_aliases (alias_lookup_key)
            WHERE review_status = 'confirmed';
        """
    )

    # ── 2b. 待補全任務表（app_layer；lookup_key 同一套 generated 正規化）──
    op.execute(
        f"""
        CREATE TABLE app_layer.company_normalization_tasks (
            task_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            raw_name            TEXT NOT NULL,
            lookup_key          TEXT
                GENERATED ALWAYS AS ({_NORMALIZE.format(col='raw_name')}) STORED,
            source_fields_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
            patent_count        INTEGER NOT NULL DEFAULT 0,
            status              TEXT NOT NULL DEFAULT 'pending',
            query_string        TEXT,
            wips_result_json    JSONB,
            note                TEXT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            resolved_at         TIMESTAMPTZ,
            CONSTRAINT company_normalization_tasks_status_check
                CHECK (status = ANY (ARRAY[
                    'pending'::text, 'queried'::text, 'review_required'::text,
                    'imported'::text, 'no_result'::text, 'dismissed'::text])),
            CONSTRAINT company_normalization_tasks_patent_count_check
                CHECK (patent_count >= 0)
        );
        """
    )
    # 同一正規化名只留一筆待補全任務。
    op.execute(
        """
        CREATE UNIQUE INDEX ux_company_normalization_tasks_lookup
            ON app_layer.company_normalization_tasks (lookup_key);
        """
    )
    op.execute(
        """
        CREATE INDEX idx_company_normalization_tasks_status
            ON app_layer.company_normalization_tasks (status, created_at);
        """
    )

    # ── 2c. 未映射公司 view：對照表（confirmed）未覆蓋的公司名 ──────────
    # 從 patent_people 的五個公司欄位展開，正規化後比對 confirmed 別稱；
    # 匹配不到者列為待正規化，依出現專利數排序供優先查 WIPS。
    op.execute(
        f"""
        CREATE VIEW derived_layer.v_unmapped_company_names AS
        WITH names AS (
            SELECT
                {_NORMALIZE.format(col='x.raw_name')} AS lookup_key,
                x.raw_name,
                x.source_field,
                pp.patent_id
            FROM core_layer.patent_people pp
            CROSS JOIN LATERAL (VALUES
                (NULLIF(btrim(pp."申請人"), ''), '申請人'),
                (NULLIF(btrim(pp."標準化申請人"), ''), '標準化申請人'),
                (NULLIF(btrim(pp."最近專利權人[US,JP,KR,CN,CA,AU]"), ''), '最近專利權人'),
                (NULLIF(btrim(pp."標準當前專利權人[US,JP,KR,CN,CA,AU]"), ''), '標準當前專利權人'),
                (NULLIF(btrim(pp."最近受讓人[US,KR,CN]"), ''), '最近受讓人')
            ) AS x(raw_name, source_field)
            WHERE x.raw_name IS NOT NULL
        )
        SELECT
            n.lookup_key,
            min(n.raw_name) AS sample_raw_name,
            array_agg(DISTINCT n.source_field ORDER BY n.source_field) AS source_fields,
            count(DISTINCT n.patent_id) AS patent_count
        FROM names n
        WHERE NOT EXISTS (
            SELECT 1
            FROM derived_layer.company_aliases ca
            WHERE ca.review_status = 'confirmed'
              AND ca.alias_lookup_key = n.lookup_key
        )
        GROUP BY n.lookup_key
        ORDER BY patent_count DESC, n.lookup_key;
        """
    )


def downgrade() -> None:
    """移除 view、任務表與 company_aliases 新增欄位（原對照資料保留）。"""
    op.execute("DROP VIEW IF EXISTS derived_layer.v_unmapped_company_names;")
    op.execute("DROP TABLE IF EXISTS app_layer.company_normalization_tasks;")
    op.execute("DROP INDEX IF EXISTS derived_layer.ux_company_aliases_lookup_confirmed;")
    op.execute(
        """
        ALTER TABLE derived_layer.company_aliases
            DROP CONSTRAINT IF EXISTS company_aliases_source_type_check,
            DROP CONSTRAINT IF EXISTS company_aliases_review_status_check,
            DROP COLUMN IF EXISTS alias_lookup_key,
            DROP COLUMN IF EXISTS source_type,
            DROP COLUMN IF EXISTS review_status,
            DROP COLUMN IF EXISTS wips_metadata_json,
            DROP COLUMN IF EXISTS updated_at;
        """
    )
