"""add workspace compose lineage table

Revision ID: 0016_workspace_compose_sources
Revises: 0015_schema_comments
Create Date: 2026-07-19

Workspace 組合建立（patent-backend-worker-plan.md「Workspace 組合建立需求」）的
lineage 底表：記錄一個組合 workspace 由哪些來源 workspace 聯集而來，以及各來源
去重前貢獻的專利件數（組合後聯集一混就算不回來，故存下供長期追蹤）。

只新增 app_layer.workspace_compose_sources 一張表；不動 core_layer、不動既有
workspaces/workspace_patents 結構與資料。compose 服務只寫本表與 workspace_patents。
"""
from __future__ import annotations

from alembic import op


revision = "0016_workspace_compose_sources"
down_revision = "0015_schema_comments"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """建立組合 workspace 的 lineage 表與反向查詢索引。"""
    op.execute(
        """
        CREATE TABLE app_layer.workspace_compose_sources (
            compose_source_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id         BIGINT NOT NULL,
            source_workspace_id  BIGINT NOT NULL,
            source_patent_count  INTEGER NOT NULL,
            created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT workspace_compose_sources_workspace_fkey
                FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE CASCADE,
            CONSTRAINT workspace_compose_sources_source_fkey
                FOREIGN KEY (source_workspace_id)
                REFERENCES app_layer.workspaces(workspace_id)
                ON DELETE RESTRICT,
            CONSTRAINT workspace_compose_sources_unique
                UNIQUE (workspace_id, source_workspace_id),
            CONSTRAINT workspace_compose_sources_not_self
                CHECK (workspace_id <> source_workspace_id),
            CONSTRAINT workspace_compose_sources_count_check
                CHECK (source_patent_count >= 0)
        );
        """
    )
    # 反向 lineage：查「哪些組合 workspace 用了某個來源」。
    op.execute(
        """
        CREATE INDEX idx_workspace_compose_sources_source
            ON app_layer.workspace_compose_sources (source_workspace_id);
        """
    )

    # 表/欄註解（沿用專案「schema 皆有中文語意註解」慣例，描述語意不寫引擎機制）。
    op.execute(
        "COMMENT ON TABLE app_layer.workspace_compose_sources IS "
        "'組合 workspace 的來源追溯：一列一個來源 workspace，記錄組合關係與各來源貢獻件數'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.workspace_compose_sources.workspace_id IS "
        "'組合後的新 workspace'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.workspace_compose_sources.source_workspace_id IS "
        "'貢獻專利的來源 workspace'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.workspace_compose_sources.source_patent_count IS "
        "'此來源貢獻的專利件數（去重前）'"
    )


def downgrade() -> None:
    """全新獨立表、無外部依賴，直接移除。"""
    op.execute("DROP TABLE app_layer.workspace_compose_sources;")
