"""simplify workspace_compose_sources to composite primary key

Revision ID: 0017_compose_composite_pk
Revises: 0016_workspace_compose_sources
Create Date: 2026-07-19

（revision id 需 <= alembic_version.version_num 的 varchar(32)，故縮短為
0017_compose_composite_pk；檔名沿用同名。）

精簡 app_layer.workspace_compose_sources：移除 surrogate 主鍵 compose_source_id
與原本的 (workspace_id, source_workspace_id) UNIQUE constraint，改用組合主鍵
PRIMARY KEY (workspace_id, source_workspace_id)。組合主鍵本身提供同樣的唯一性，
故不再需要獨立 unique constraint。

0016 已套用、不得改其意義；本檔為新的 0017，down_revision=0016。兩個 FK
（workspace_id CASCADE、source_workspace_id RESTRICT）、兩個 CHECK
（workspace_id<>source_workspace_id、source_patent_count>=0）、source 反向 index
與 table／column 註解皆保留不動，僅動主鍵結構。表目前 0 筆，變更安全。
"""
from __future__ import annotations

from alembic import op


revision = "0017_compose_composite_pk"
down_revision = "0016_workspace_compose_sources"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """移除 surrogate PK 與 compose_source_id，改用 (workspace_id, source_workspace_id) 組合主鍵。"""
    # 先卸掉舊 unique（與新組合主鍵重複）與 surrogate 主鍵，才能移除 compose_source_id 欄。
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "DROP CONSTRAINT workspace_compose_sources_unique;"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "DROP CONSTRAINT workspace_compose_sources_pkey;"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "DROP COLUMN compose_source_id;"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "ADD CONSTRAINT workspace_compose_sources_pkey "
        "PRIMARY KEY (workspace_id, source_workspace_id);"
    )


def downgrade() -> None:
    """還原 compose_source_id identity 主鍵與原 (workspace_id, source_workspace_id) UNIQUE。"""
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "DROP CONSTRAINT workspace_compose_sources_pkey;"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "ADD COLUMN compose_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY;"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "ADD CONSTRAINT workspace_compose_sources_pkey PRIMARY KEY (compose_source_id);"
    )
    op.execute(
        "ALTER TABLE app_layer.workspace_compose_sources "
        "ADD CONSTRAINT workspace_compose_sources_unique "
        "UNIQUE (workspace_id, source_workspace_id);"
    )
