"""core layer 精簡：移除無必要技術 id 與 dedupe_key，改用專利號＋raw_record_id 複合鍵

Revision ID: 0020_core_layer_simplify
Revises: 0019_raw_layer_simplify
Create Date: 2026-07-20

移除 patent_people.id、patent_attributes.id、patent_sources.id 三個無業務用途的 surrogate
id 與 patent_sources.dedupe_key；改用：
  patent_people      PRIMARY KEY (patent_id)
  patent_attributes  PRIMARY KEY (patent_id, raw_record_id)
  patent_sources     PRIMARY KEY (patent_id, raw_record_id)
去重改只用既有專利號查找順序（授權公告號→審查公告號→未審查公開號(轉換後)→申請號(轉換後)+
country_code/database_name），不再產生/寫入 dedupe_key，也不進 report_patent_base。
patents.id、raw_records.id 保留作 FK。patents/patent_people 原始欄位不變。

前提：0019（raw layer）已套用（source_file_id 已從 patent_sources/patent_attributes 移除）。
套用前查重（patent_people.patent_id、patent_attributes/(patent_id,raw_record_id)、
patent_sources/(patent_id,raw_record_id)）須為 0，否則不得套用（已於套用前確認 932/932/932、
0 重複、0 NULL raw_record_id）。

downgrade 可重建技術 id 與舊 constraint；**dedupe_key 原值無法無損重建**（原為 WIPS 識別號
快照），downgrade 以 'RESTORED|patent_id|raw_record_id' 占位並標記，report_patent_base.dedupe_key
重建為可空、待下次 refresh 重填；patent_attributes.raw_record_id 的 FK 由 CASCADE 還原為 SET NULL。
"""
from __future__ import annotations

from alembic import op


revision = "0020_core_layer_simplify"
down_revision = "0019_raw_layer_simplify"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """三張表改用專利號/複合鍵、移除 surrogate id 與 dedupe_key。"""
    # ── patent_people：PK 由 id 改為 patent_id（已有 UNIQUE(patent_id) 佐證唯一）──
    op.execute("ALTER TABLE core_layer.patent_people DROP CONSTRAINT patent_people_pkey;")
    op.execute("ALTER TABLE core_layer.patent_people DROP CONSTRAINT patent_people_patent_id_key;")
    op.execute("ALTER TABLE core_layer.patent_people DROP COLUMN id;")
    op.execute(
        "ALTER TABLE core_layer.patent_people "
        "ADD CONSTRAINT patent_people_pkey PRIMARY KEY (patent_id);"
    )

    # ── patent_attributes：PK 改 (patent_id, raw_record_id)──
    # raw_record_id 原可空且 FK ON DELETE SET NULL；複合 PK 需 NOT NULL，故先設 NOT NULL 並
    # 將 FK 改為 CASCADE（SET NULL 與 NOT NULL 不相容）。查重已確認 0 NULL raw_record_id。
    op.execute("ALTER TABLE core_layer.patent_attributes DROP CONSTRAINT patent_attributes_raw_record_id_fkey;")
    op.execute("ALTER TABLE core_layer.patent_attributes ALTER COLUMN raw_record_id SET NOT NULL;")
    op.execute(
        "ALTER TABLE core_layer.patent_attributes "
        "ADD CONSTRAINT patent_attributes_raw_record_id_fkey "
        "FOREIGN KEY (raw_record_id) REFERENCES raw_layer.raw_records(id) ON DELETE CASCADE;"
    )
    op.execute("ALTER TABLE core_layer.patent_attributes DROP CONSTRAINT patent_attributes_pkey;")
    op.execute("ALTER TABLE core_layer.patent_attributes DROP COLUMN id;")
    op.execute(
        "ALTER TABLE core_layer.patent_attributes "
        "ADD CONSTRAINT patent_attributes_pkey PRIMARY KEY (patent_id, raw_record_id);"
    )

    # ── patent_sources：PK 改 (patent_id, raw_record_id)、移除 id 與 dedupe_key ──
    # 既有 UNIQUE(patent_id, raw_record_id) 佐證唯一，升格為 PK。
    op.execute("ALTER TABLE core_layer.patent_sources DROP CONSTRAINT patent_sources_pkey;")
    op.execute(
        "ALTER TABLE core_layer.patent_sources "
        "DROP CONSTRAINT patent_sources_patent_id_raw_record_id_key;"
    )
    op.execute("DROP INDEX IF EXISTS core_layer.idx_patent_sources_dedupe_key;")
    op.execute("ALTER TABLE core_layer.patent_sources DROP COLUMN dedupe_key;")
    op.execute("ALTER TABLE core_layer.patent_sources DROP COLUMN id;")
    op.execute(
        "ALTER TABLE core_layer.patent_sources "
        "ADD CONSTRAINT patent_sources_pkey PRIMARY KEY (patent_id, raw_record_id);"
    )

    # ── report_patent_base：移除 dedupe_key 欄（不再由 refresh 寫入）──
    op.execute("ALTER TABLE derived_layer.report_patent_base DROP COLUMN dedupe_key;")

    # ── 更新 schema 註解（表級口徑）──
    op.execute(
        "COMMENT ON TABLE core_layer.patent_sources IS "
        "'專利與原始匯入紀錄的來源對應；主鍵 (patent_id, raw_record_id)，不再用 surrogate id 或 dedupe_key'"
    )


def downgrade() -> None:
    """重建 surrogate id、dedupe_key 與舊 constraint；dedupe_key 原值無法無損重建。"""
    # ── report_patent_base：重建 dedupe_key 欄（可空，待下次 refresh 重填）──
    op.execute("ALTER TABLE derived_layer.report_patent_base ADD COLUMN dedupe_key TEXT;")

    # ── patent_sources：還原 id、dedupe_key、舊 PK/unique/index ──
    op.execute("ALTER TABLE core_layer.patent_sources DROP CONSTRAINT patent_sources_pkey;")
    op.execute("ALTER TABLE core_layer.patent_sources ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE core_layer.patent_sources ADD CONSTRAINT patent_sources_pkey PRIMARY KEY (id);")
    op.execute(
        "ALTER TABLE core_layer.patent_sources "
        "ADD CONSTRAINT patent_sources_patent_id_raw_record_id_key UNIQUE (patent_id, raw_record_id);"
    )
    # dedupe_key 原值（WIPS 識別號快照）已遺失；以可推得的占位值重建並標記，非原始值。
    op.execute("ALTER TABLE core_layer.patent_sources ADD COLUMN dedupe_key TEXT;")
    op.execute(
        "UPDATE core_layer.patent_sources "
        "SET dedupe_key = 'RESTORED|' || patent_id || '|' || raw_record_id;"
    )
    op.execute("ALTER TABLE core_layer.patent_sources ALTER COLUMN dedupe_key SET NOT NULL;")
    op.execute("CREATE INDEX idx_patent_sources_dedupe_key ON core_layer.patent_sources (dedupe_key);")

    # ── patent_attributes：還原 id 與可空 raw_record_id + SET NULL FK ──
    op.execute("ALTER TABLE core_layer.patent_attributes DROP CONSTRAINT patent_attributes_pkey;")
    op.execute("ALTER TABLE core_layer.patent_attributes ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE core_layer.patent_attributes ADD CONSTRAINT patent_attributes_pkey PRIMARY KEY (id);")
    op.execute("ALTER TABLE core_layer.patent_attributes DROP CONSTRAINT patent_attributes_raw_record_id_fkey;")
    op.execute("ALTER TABLE core_layer.patent_attributes ALTER COLUMN raw_record_id DROP NOT NULL;")
    op.execute(
        "ALTER TABLE core_layer.patent_attributes "
        "ADD CONSTRAINT patent_attributes_raw_record_id_fkey "
        "FOREIGN KEY (raw_record_id) REFERENCES raw_layer.raw_records(id) ON DELETE SET NULL;"
    )

    # ── patent_people：還原 id 與 UNIQUE(patent_id)──
    op.execute("ALTER TABLE core_layer.patent_people DROP CONSTRAINT patent_people_pkey;")
    op.execute("ALTER TABLE core_layer.patent_people ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE core_layer.patent_people ADD CONSTRAINT patent_people_pkey PRIMARY KEY (id);")
    op.execute(
        "ALTER TABLE core_layer.patent_people "
        "ADD CONSTRAINT patent_people_patent_id_key UNIQUE (patent_id);"
    )

    op.execute(
        "COMMENT ON TABLE core_layer.patent_sources IS "
        "'專利與原始匯入紀錄的來源對應，含去重鍵'"
    )
