"""derived+app 併表：derived/app 各縮成 3 張實體 table（Green，含資料搬移）

Revision ID: 0021_derived_app_consolidation
Revises: 0020_core_layer_simplify
Create Date: 2026-07-20

最終 app_layer=workspaces/workflow_runs/workflow_outputs、derived_layer=company_aliases/
topic_runs/topic_assignments；report_patent_base/family_country/family_quality 為相容 VIEW。

資料搬移策略：舊表以 SET SCHEMA 移到 legacy_0021（保留完整結構與值），作為新表資料來源
與 downgrade 的無損還原來源；app_layer/derived_layer 只留目標 3+3。
- workflow_runs ← processing_jobs（job_id 保留為 run_id）＋analysis_runs＋company_normalization_tasks
  ＋每個 topic_run 一個 clustering run；不同來源 ID 以 _run_map 分配、不碰撞，保存 legacy_source/legacy_id。
- workflow_outputs ← analysis_outputs（data_json）＋export_runs（artifact_manifest_json，含 sha256=file_hash），
  版本 (run_id,output_type,version) 不覆蓋。
- topic_runs ← 舊 topic_runs（run_id 保留、workflow_run_id 連新 run），topics/candidates/assignments
  併入 topic_state_json；topic_assignments 保留（run_id,patent_id 一列，topic_key=topic_code）。
- report_* VIEW = SELECT * FROM legacy_0021.report_*（保留既有欄位與值，不只 patent_id）。

downgrade：移除新表與 VIEW → 舊表由 legacy_0021 搬回 → 還原 workspaces 舊欄 → 移除 legacy_0021。
（0020.downgrade 會對搬回的 report_patent_base 補回 dedupe_key。）
"""
from __future__ import annotations

from alembic import op


revision = "0021_derived_app_consolidation"
down_revision = "0020_core_layer_simplify"
branch_labels = None
depends_on = None

_APP_LEGACY = ("workspace_patents", "workspace_compose_sources", "processing_jobs",
               "analysis_runs", "analysis_outputs", "export_runs", "company_normalization_tasks")
_DERIVED_LEGACY = ("topic_assignments", "topic_candidates", "topics", "topic_runs",
                   "report_patent_base", "report_family_country", "report_family_quality")


def upgrade() -> None:
    """derived/app 各併成 3 張實體 table，完整搬移業務資料。"""
    op.execute("CREATE SCHEMA IF NOT EXISTS legacy_0021")

    # ═══ workspaces：加 patent_ids_json/settings_json、由 workspace_patents+compose_sources 回填後去舊欄 ═══
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN patent_ids_json JSONB")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN settings_json JSONB")
    op.execute(
        """
        UPDATE app_layer.workspaces w SET
            patent_ids_json = COALESCE((
                SELECT jsonb_agg(pid ORDER BY pid)
                FROM (SELECT DISTINCT wp.patent_id AS pid
                      FROM app_layer.workspace_patents wp WHERE wp.workspace_id = w.workspace_id) s
            ), '[]'::jsonb),
            settings_json = jsonb_strip_nulls(jsonb_build_object(
                'description', w.description, 'filters', w.filter_json, 'parameters', w.parameters_json,
                'created_by', w.created_by, 'created_at', w.created_at,
                'updated_at', w.updated_at, 'archived_at', w.archived_at,
                'composed_from', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                        'source_workspace_id', cs.source_workspace_id,
                        'source_patent_count', cs.source_patent_count) ORDER BY cs.source_workspace_id)
                    FROM app_layer.workspace_compose_sources cs WHERE cs.workspace_id = w.workspace_id
                ), '[]'::jsonb)))
        """
    )
    op.execute("ALTER TABLE app_layer.workspaces ALTER COLUMN patent_ids_json SET DEFAULT '[]'::jsonb")
    op.execute("ALTER TABLE app_layer.workspaces ALTER COLUMN patent_ids_json SET NOT NULL")
    op.execute("ALTER TABLE app_layer.workspaces ALTER COLUMN settings_json SET DEFAULT '{}'::jsonb")
    op.execute("ALTER TABLE app_layer.workspaces ALTER COLUMN settings_json SET NOT NULL")

    # ═══ 舊表移到 legacy_0021（保留完整結構與值）═══
    for t in _APP_LEGACY:
        op.execute(f"ALTER TABLE app_layer.{t} SET SCHEMA legacy_0021")
    for t in _DERIVED_LEGACY:
        op.execute(f"ALTER TABLE derived_layer.{t} SET SCHEMA legacy_0021")
    for col in ("description", "filter_json", "parameters_json", "created_by",
                "created_at", "updated_at", "archived_at"):
        op.execute(f"ALTER TABLE app_layer.workspaces DROP COLUMN {col}")

    # ═══ workflow_runs ═══
    op.execute(
        """
        CREATE TABLE app_layer.workflow_runs (
            run_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id      BIGINT,
            run_type          TEXT NOT NULL,
            status            TEXT NOT NULL DEFAULT 'queued',
            request_key       TEXT,
            request_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
            worker_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT workflow_runs_workspace_fkey FOREIGN KEY (workspace_id)
                REFERENCES app_layer.workspaces(workspace_id) ON DELETE SET NULL,
            CONSTRAINT workflow_runs_request_key_key UNIQUE (request_key),
            CONSTRAINT workflow_runs_status_check
                CHECK (status IN ('queued','running','succeeded','failed','cancelled'))
        )
        """
    )
    op.execute("CREATE INDEX idx_workflow_runs_claim ON app_layer.workflow_runs (status, run_id)")

    # run_id 分配：processing_jobs 保留 job_id；其餘偏移不碰撞（保 legacy_source/legacy_id）
    op.execute("CREATE TEMP TABLE _run_map (legacy_source TEXT, legacy_id BIGINT, run_id BIGINT)")
    op.execute("INSERT INTO _run_map SELECT 'processing_job', job_id, job_id FROM legacy_0021.processing_jobs")
    op.execute(
        "INSERT INTO _run_map SELECT 'analysis', analysis_id, "
        "(SELECT COALESCE(max(run_id),0) FROM _run_map) + row_number() OVER (ORDER BY analysis_id) "
        "FROM legacy_0021.analysis_runs"
    )
    op.execute(
        "INSERT INTO _run_map SELECT 'company_normalization', task_id, "
        "(SELECT COALESCE(max(run_id),0) FROM _run_map) + row_number() OVER (ORDER BY task_id) "
        "FROM legacy_0021.company_normalization_tasks"
    )
    op.execute(
        "INSERT INTO _run_map SELECT 'topic_run', run_id, "
        "(SELECT COALESCE(max(run_id),0) FROM _run_map) + row_number() OVER (ORDER BY run_id) "
        "FROM legacy_0021.topic_runs"
    )
    # processing_jobs → workflow_runs（job_id→run_id、progress 存 worker_state）
    op.execute(
        """
        INSERT INTO app_layer.workflow_runs (run_id, workspace_id, run_type, status, request_key, request_json, worker_state_json)
        SELECT m.run_id, j.workspace_id, j.job_type, j.status, j.idempotency_key,
               COALESCE(j.payload_json, '{}'::jsonb),
               jsonb_build_object('legacy_source','processing_job','legacy_id',j.job_id,'progress',j.progress_percent)
        FROM legacy_0021.processing_jobs j JOIN _run_map m ON m.legacy_source='processing_job' AND m.legacy_id=j.job_id
        """
    )
    # analysis_runs → workflow_runs
    op.execute(
        """
        INSERT INTO app_layer.workflow_runs (run_id, run_type, status, request_json, worker_state_json)
        SELECT m.run_id, 'analysis:'||a.analysis_type,
               CASE a.status WHEN 'pending' THEN 'queued' WHEN 'completed' THEN 'succeeded' ELSE a.status END,
               jsonb_build_object('analysis_name',a.analysis_name,'analysis_type',a.analysis_type,
                   'filters',a.filter_json,'parameters',a.parameters_json,'selected_patent_ids',a.selected_patent_ids_json),
               jsonb_strip_nulls(jsonb_build_object('legacy_source','analysis','legacy_id',a.analysis_id,'orig_status',a.status))
        FROM legacy_0021.analysis_runs a JOIN _run_map m ON m.legacy_source='analysis' AND m.legacy_id=a.analysis_id
        """
    )
    # company_normalization_tasks → workflow_runs
    op.execute(
        """
        INSERT INTO app_layer.workflow_runs (run_id, run_type, status, request_json, worker_state_json)
        SELECT m.run_id, 'company_normalization',
               CASE t.status WHEN 'pending' THEN 'queued' WHEN 'queried' THEN 'running'
                    WHEN 'review_required' THEN 'running' WHEN 'imported' THEN 'succeeded'
                    WHEN 'no_result' THEN 'failed' WHEN 'dismissed' THEN 'cancelled' ELSE 'queued' END,
               jsonb_build_object('raw_name',t.raw_name),
               jsonb_build_object('legacy_source','company_normalization','legacy_id',t.task_id,'orig_status',t.status,'patent_count',t.patent_count)
        FROM legacy_0021.company_normalization_tasks t JOIN _run_map m ON m.legacy_source='company_normalization' AND m.legacy_id=t.task_id
        """
    )
    # 每個 topic_run 一個 clustering workflow_run
    op.execute(
        """
        INSERT INTO app_layer.workflow_runs (run_id, workspace_id, run_type, status, worker_state_json)
        SELECT m.run_id, tr.workspace_id, 'clustering:'||tr.source_field,
               CASE tr.status WHEN 'pending' THEN 'queued' WHEN 'completed' THEN 'succeeded'
                    WHEN 'needs_review' THEN 'running' ELSE tr.status END,
               jsonb_build_object('legacy_source','topic_run','legacy_id',tr.run_id)
        FROM legacy_0021.topic_runs tr JOIN _run_map m ON m.legacy_source='topic_run' AND m.legacy_id=tr.run_id
        """
    )
    # 顯式灌入 run_id 後推進 IDENTITY 序列至 max+1，避免之後 default run_id 從 1 起與遷入 ID 碰撞
    op.execute(
        "SELECT setval(pg_get_serial_sequence('app_layer.workflow_runs','run_id'), "
        "(SELECT COALESCE(max(run_id),0) FROM app_layer.workflow_runs) + 1, false)"
    )

    # ═══ workflow_outputs ═══
    op.execute(
        """
        CREATE TABLE app_layer.workflow_outputs (
            run_id                 BIGINT NOT NULL,
            output_type            TEXT NOT NULL,
            version                INTEGER NOT NULL,
            data_json              JSONB NOT NULL DEFAULT '{}'::jsonb,
            artifact_manifest_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            exported_at            TIMESTAMPTZ,
            CONSTRAINT workflow_outputs_pkey PRIMARY KEY (run_id, output_type, version),
            CONSTRAINT workflow_outputs_run_fkey FOREIGN KEY (run_id)
                REFERENCES app_layer.workflow_runs(run_id) ON DELETE CASCADE,
            CONSTRAINT workflow_outputs_version_check CHECK (version >= 1)
        )
        """
    )
    # analysis_outputs → workflow_outputs
    op.execute(
        """
        INSERT INTO app_layer.workflow_outputs (run_id, output_type, version, data_json)
        SELECT m.run_id, ao.output_type,
               row_number() OVER (PARTITION BY ao.analysis_id, ao.output_type ORDER BY ao.output_id),
               jsonb_build_object('legacy_source','analysis_output','legacy_id',ao.output_id,
                   'output_name',ao.output_name,'result',ao.result_json)
        FROM legacy_0021.analysis_outputs ao JOIN _run_map m ON m.legacy_source='analysis' AND m.legacy_id=ao.analysis_id
        """
    )
    # export_runs → workflow_outputs（artifact_manifest 含 sha256=file_hash）
    op.execute(
        """
        INSERT INTO app_layer.workflow_outputs (run_id, output_type, version, artifact_manifest_json, exported_at)
        SELECT m.run_id, 'export:'||er.export_type,
               row_number() OVER (PARTITION BY er.analysis_id, er.export_type ORDER BY er.export_id),
               jsonb_build_object('legacy_source','export_run','legacy_id',er.export_id,
                   'artifact_key',er.file_path,'sha256',er.file_hash,'parameters',er.parameters_json),
               er.created_at
        FROM legacy_0021.export_runs er JOIN _run_map m ON m.legacy_source='analysis' AND m.legacy_id=er.analysis_id
        """
    )

    # ═══ derived topic_runs / topic_assignments ═══
    op.execute(
        """
        CREATE TABLE derived_layer.topic_runs (
            run_id           BIGINT PRIMARY KEY,
            workflow_run_id  BIGINT NOT NULL,
            previous_run_id  BIGINT,
            source_field     TEXT NOT NULL,
            topic_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            artifact_key     TEXT,
            CONSTRAINT topic_runs_workflow_fkey FOREIGN KEY (workflow_run_id)
                REFERENCES app_layer.workflow_runs(run_id) ON DELETE CASCADE,
            CONSTRAINT topic_runs_previous_fkey FOREIGN KEY (previous_run_id)
                REFERENCES derived_layer.topic_runs(run_id) ON DELETE SET NULL,
            CONSTRAINT topic_runs_source_field_check
                CHECK (source_field IN ('wips_independent_claims','effect_summary'))
        )
        """
    )
    # 舊 topic_runs → 新（topics/candidates/assignments 併入 topic_state_json；previous_run_id 後補）
    op.execute(
        """
        INSERT INTO derived_layer.topic_runs (run_id, workflow_run_id, source_field, topic_state_json, artifact_key)
        SELECT tr.run_id, m.run_id, tr.source_field,
               jsonb_strip_nulls(jsonb_build_object(
                   'legacy_source','topic_run','run_mode',tr.run_mode,'status',tr.status,
                   'topics', (SELECT jsonb_agg(to_jsonb(t.*)) FROM legacy_0021.topics t WHERE t.created_run_id=tr.run_id),
                   'candidates', (SELECT jsonb_agg(to_jsonb(tc.*)) FROM legacy_0021.topic_candidates tc WHERE tc.run_id=tr.run_id),
                   'assignments', (SELECT jsonb_agg(to_jsonb(ta.*)) FROM legacy_0021.topic_assignments ta WHERE ta.assigned_run_id=tr.run_id),
                   'legacy_topic_run', to_jsonb(tr.*))),
               (to_jsonb(tr.*)->>'model_artifact_path')
        FROM legacy_0021.topic_runs tr JOIN _run_map m ON m.legacy_source='topic_run' AND m.legacy_id=tr.run_id
        """
    )
    op.execute(
        """
        UPDATE derived_layer.topic_runs nt
        SET previous_run_id = lt.previous_run_id
        FROM legacy_0021.topic_runs lt
        WHERE lt.run_id = nt.run_id AND lt.previous_run_id IS NOT NULL
        """
    )
    op.execute(
        """
        CREATE TABLE derived_layer.topic_assignments (
            run_id               BIGINT NOT NULL,
            patent_id            BIGINT NOT NULL,
            topic_key            TEXT NOT NULL,
            distance_to_centroid DOUBLE PRECISION,
            CONSTRAINT topic_assignments_pkey PRIMARY KEY (run_id, patent_id),
            CONSTRAINT topic_assignments_run_fkey FOREIGN KEY (run_id)
                REFERENCES derived_layer.topic_runs(run_id) ON DELETE CASCADE,
            CONSTRAINT topic_assignments_patent_fkey FOREIGN KEY (patent_id)
                REFERENCES core_layer.patents(id) ON DELETE CASCADE
        )
        """
    )
    # 舊 topic_assignments → 新（一 (run,patent) 一列，topic_key=topic_code）
    op.execute(
        """
        INSERT INTO derived_layer.topic_assignments (run_id, patent_id, topic_key, distance_to_centroid)
        SELECT DISTINCT ON (ta.assigned_run_id, ta.patent_id)
               ta.assigned_run_id, ta.patent_id,
               -- 只取正式 topic_code；映射不到時回 NULL → 撞 topic_key NOT NULL → migration 明確失敗，不塞數字字串
               (SELECT t.topic_code FROM legacy_0021.topics t
                WHERE t.topic_id=ta.topic_id AND t.workspace_id=ta.workspace_id AND t.source_field=ta.source_field),
               ta.distance_to_centroid
        FROM legacy_0021.topic_assignments ta
        ORDER BY ta.assigned_run_id, ta.patent_id, ta.assignment_id DESC
        """
    )

    # ═══ report_* 相容 VIEW（保留既有欄位與值）═══
    op.execute("CREATE VIEW derived_layer.report_patent_base AS SELECT * FROM legacy_0021.report_patent_base")
    op.execute("CREATE VIEW derived_layer.report_family_country AS SELECT * FROM legacy_0021.report_family_country")
    op.execute("CREATE VIEW derived_layer.report_family_quality AS SELECT * FROM legacy_0021.report_family_quality")

    op.execute("DROP TABLE _run_map")


def downgrade() -> None:
    """移除新表與 VIEW，舊表由 legacy_0021 無損搬回，還原 workspaces 舊欄。"""
    op.execute("DROP VIEW IF EXISTS derived_layer.report_patent_base")
    op.execute("DROP VIEW IF EXISTS derived_layer.report_family_country")
    op.execute("DROP VIEW IF EXISTS derived_layer.report_family_quality")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_assignments CASCADE")
    op.execute("DROP TABLE IF EXISTS derived_layer.topic_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS app_layer.workflow_outputs CASCADE")
    op.execute("DROP TABLE IF EXISTS app_layer.workflow_runs CASCADE")

    for t in _DERIVED_LEGACY:
        op.execute(f"ALTER TABLE legacy_0021.{t} SET SCHEMA derived_layer")
    for t in _APP_LEGACY:
        op.execute(f"ALTER TABLE legacy_0021.{t} SET SCHEMA app_layer")

    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN description TEXT")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN filter_json JSONB NOT NULL DEFAULT '{}'::jsonb")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN created_by TEXT")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now()")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now()")
    op.execute("ALTER TABLE app_layer.workspaces ADD COLUMN archived_at TIMESTAMPTZ")
    op.execute(
        """
        UPDATE app_layer.workspaces SET
            description = settings_json->>'description',
            filter_json = COALESCE(settings_json->'filters', '{}'::jsonb),
            parameters_json = COALESCE(settings_json->'parameters', '{}'::jsonb),
            created_by = settings_json->>'created_by',
            created_at = COALESCE((settings_json->>'created_at')::timestamptz, created_at),
            updated_at = COALESCE((settings_json->>'updated_at')::timestamptz, updated_at),
            archived_at = (settings_json->>'archived_at')::timestamptz
        """
    )
    op.execute("ALTER TABLE app_layer.workspaces DROP COLUMN patent_ids_json")
    op.execute("ALTER TABLE app_layer.workspaces DROP COLUMN settings_json")

    op.execute("DROP SCHEMA IF EXISTS legacy_0021")
