"""market_evidence 證據庫表：derived_layer.market_evidence 8 欄定版（Green）。

Revision ID: 0023_market_evidence
Revises: fd301dee99c3
Create Date: 2026-07-22

規格唯一來源：.agents/skills/market-data-flow.md「證據庫表」節。
8 欄定版：id/kind/scope/target/payload_json/source_url/summary/accepted_at。
索引 (kind,scope,target) 供 get_evidence 查詢；唯一約束 (scope,source_url) 防同 scope 同 URL 重複收錄。
本表只存已接受證據（accepted_at 落款）；不可 UPDATE 值，作廢＝舊列 payload_json 標 superseded＋新列 append。
"""
from __future__ import annotations

from alembic import op


revision = "0023_market_evidence"
down_revision = "fd301dee99c3"
branch_labels = None
depends_on = None

# kind 白名單（CHECK 與 evidence_model.KINDS 一致）
_KINDS = "'market_size','region_trend','customer','key_player','pain_point'"


def upgrade() -> None:
    op.execute(f"""
        CREATE TABLE derived_layer.market_evidence (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind         TEXT NOT NULL CHECK (kind IN ({_KINDS})),
            scope        TEXT NOT NULL,
            target       TEXT,
            payload_json JSONB NOT NULL,
            source_url   TEXT NOT NULL,
            summary      TEXT NOT NULL,
            accepted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_market_evidence_scope_url UNIQUE (scope, source_url)
        )
    """)
    # 查詢鍵索引：get_evidence 依 kind／scope／target 過濾
    op.execute(
        "CREATE INDEX ix_market_evidence_kind_scope_target "
        "ON derived_layer.market_evidence (kind, scope, target)"
    )
    op.execute(
        "COMMENT ON TABLE derived_layer.market_evidence IS "
        "'市場資料證據庫（唯一新表）：只存使用者接受的證據（accepted_at 落款）；"
        "不可 UPDATE 值，作廢走 payload_json superseded 標記＋新列 append'"
    )


def downgrade() -> None:
    # DROP TABLE 會一併移除 index 與 unique constraint；索引先顯式移除以求 downgrade 完整可讀
    op.execute("DROP INDEX IF EXISTS derived_layer.ix_market_evidence_kind_scope_target")
    op.execute("DROP TABLE IF EXISTS derived_layer.market_evidence")
