"""app_layer.import_blobs：匯入上傳檔案內容的跨容器傳輸表。

Revision ID: 0024_import_blobs
Revises: 0023_market_evidence
Create Date: 2026-07-23

背景：Railway 上 backend 與 worker 是**不同容器**、檔案系統不共享（Railway volume 只能綁單一
服務，建出來是兩個獨立 volume），worker 領到 patent_import job 後在自己的檔案系統找不到
backend 寫的上傳檔而失敗。兩容器本來就共用同一個 PostgreSQL，故以 DB 當跨容器傳輸媒介。

為何**另立新表**而非塞既有 app_layer.workflow_runs.request_json：request_json 被
job_repository._SELECT_COLUMNS 帶進**每一次** job 查詢（get_job／list_jobs／claim_next_job），
list_jobs 上限 200 筆；把數 MB base64 塞進 JSONB 會讓每次輪詢佇列都拖回上百 MB，且 JSONB
需 parse、base64 另放大 33%。改用獨立表＋bytea，job 查詢完全不碰內容，只有 worker 取檔時
才依 blob_id 撈一次。

欄位只留必要的：內容（content bytea）、原檔名（worker 依副檔名選 parser）、hash 與大小
（完整性驗證）；能推導的不重複存。內容為**短生命週期**——worker 匯入完（含重複檔）即刪，
追溯靠 raw_records.source_file_hash（0019 起 source_files 表已移除）。
"""
from __future__ import annotations

from alembic import op


revision = "0024_import_blobs"
down_revision = "0023_market_evidence"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE app_layer.import_blobs (
            blob_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            original_filename TEXT NOT NULL,
            content           BYTEA NOT NULL DEFAULT ''::bytea,
            file_hash         TEXT,
            byte_size         BIGINT,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    # 大 bytea 由 TOAST 外置壓縮；上傳內容多為已壓縮的 xlsx，再壓沒有效益且吃 CPU，
    # 故關閉壓縮只走外置儲存（EXTERNAL），讓分塊 append 與整取都少一次壓縮／解壓。
    op.execute("ALTER TABLE app_layer.import_blobs ALTER COLUMN content SET STORAGE EXTERNAL")
    op.execute(
        "COMMENT ON TABLE app_layer.import_blobs IS "
        "'匯入上傳檔案內容的跨容器傳輸表（backend 寫、worker 讀）：Railway 上兩容器檔案系統"
        "不共享，改以共用 PostgreSQL 傳遞。內容為短生命週期，worker 匯入完即刪；"
        "追溯靠 raw_records.source_file_hash'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.import_blobs.content IS "
        "'檔案原始位元組；上傳端分塊 append（content || chunk），不整包進記憶體'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.import_blobs.file_hash IS "
        "'SHA-256（上傳完成才落款）；worker 取檔後重算比對，不符即拒絕匯入'"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS app_layer.import_blobs")
