"""app_layer.workspace_documents：workspace 級技術文獻（PDF）長期保存表。

Revision ID: 0027_workspace_documents
Revises: 0026_patent_main_figure
Create Date: 2026-07-23

背景：市場研究線需要使用者上傳產業／技術文獻（PDF），供 CLI 推導產品定義（scope）與
市場證據。文獻須**長期保存**——每次市場研究都要重讀，不是一次性消費。

為何**另立新表**而非沿用 app_layer.import_blobs：後者是**用完即刪**的短生命週期上傳暫存
（0024 docstring 明載：worker 匯入完，含重複檔，即 delete_blob），且**無 workspace_id**。
技術文獻的生命週期與歸屬都相反。兩種生命週期混用會讓刪除邏輯必須先判斷用途，
一旦判斷失誤就是誤刪使用者長期資料，故物理分表。

為何**不塞 app_layer.workspaces.settings_json**：該欄被每一次 workspace 查詢
（list/detail/compose）帶回，數 MB 的 PDF 塞進 JSONB 會讓所有 workspace 查詢都拖回大量
內容，且 JSONB 需 parse、base64 另放大 33%。判準同 0024 否決 workflow_runs.request_json。

欄位 **6 欄封頂**：不存 byte_size（`length(content)` 可得）、不存 mime（magic number 推導），
沿 0024／patent_figures 的精簡口徑，能推導的不重複存。
"""
from __future__ import annotations

from alembic import op


revision = "0027_workspace_documents"
down_revision = "0026_patent_main_figure"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE app_layer.workspace_documents (
            document_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id      BIGINT NOT NULL
                REFERENCES app_layer.workspaces(workspace_id) ON DELETE CASCADE,
            original_filename TEXT NOT NULL,
            content           BYTEA NOT NULL DEFAULT ''::bytea,
            file_hash         TEXT,
            uploaded_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    # 依 workspace 列文獻是唯一的查詢型態（列表端點），FK 欄建索引避免全表掃。
    op.execute(
        "CREATE INDEX workspace_documents_workspace_idx "
        "ON app_layer.workspace_documents (workspace_id)"
    )
    # 大 bytea 由 TOAST 外置壓縮；PDF 內部已壓縮，再壓沒有效益且吃 CPU，
    # 故關閉壓縮只走外置儲存（EXTERNAL），讓分塊 append 與整取都少一次壓縮／解壓。
    op.execute(
        "ALTER TABLE app_layer.workspace_documents ALTER COLUMN content SET STORAGE EXTERNAL"
    )
    op.execute(
        "COMMENT ON TABLE app_layer.workspace_documents IS "
        "'workspace 級技術文獻（PDF）長期保存：供市場研究線推導產品定義與市場證據，"
        "CLI 每次研究重讀。與用完即刪的 import_blobs 物理分離，避免刪除邏輯誤判用途'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.workspace_documents.content IS "
        "'檔案原始位元組；上傳端分塊 append（content || chunk），不整包進記憶體。"
        "⚠ 列表查詢一律不得選此欄，只在單筆取用時撈'"
    )
    op.execute(
        "COMMENT ON COLUMN app_layer.workspace_documents.file_hash IS "
        "'SHA-256（上傳完成才落款）；取用端可重算比對確認完整性'"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS app_layer.workspace_documents")
