"""市場資料線底層兩表：derived_layer.market_documents（PDF metadata）＋
derived_layer.market_doc_summaries（AI 摘要版本）。

Revision ID: 0034_market_doc_summary
Revises: 0033_company_alias_ai_suggested
Create Date: 2026-07-24

背景（2026-07-23／24 定案）：舊「AI 上網搜集市場資料」設計作廢，改為**使用者上傳市場 PDF
→ AI 讀 PDF 產結構化＋敘述摘要 → 逐筆確認、可重跑**。本 migration 只建底層兩表。

## 為何不沿用既有 derived_layer.market_evidence
market_evidence 是為「AI 上網搜集網搜證據」設計：以 `source_url` 當去重鍵（網頁來源）、
`accepted_at` 為單筆網搜候選的接受落款、append-only 靠 supersede 標記。新流程來源改為
**上傳的 PDF 檔**（`source_document`，非 URL），且採**整份摘要版本化**（重跑產生新版本、
舊版標 status=superseded），心智模型與 report_artifacts 一致，與逐筆網搜證據不同。硬套
market_evidence 會讓 source_url／唯一約束語意錯位，故另立表。（舊 market_evidence 待批3
同一 migration 移除，本批不動。）

## market_documents（PDF metadata；內容落檔案系統）
與 workspace_documents（0027，內容存 bytea in DB）**刻意不同**：市場 PDF 的讀取者是**本機
Companion 驅動的 CLI**，非 Railway 容器，故內容落**檔案系統目錄**（MARKET_DOC_ROOT，NAS 佔位，
換 NAS 只改設定），DB 只存 metadata。因內容不在 DB，**須存 byte_size**（無法 length(content)
推導，與 0027 精簡口徑的差異來自落點不同）；stored_filename 為落地檔名，供列出與刪檔定位。

## market_doc_summaries（AI 摘要版本）
- `status` 兩態（current／superseded）由 CHECK 約束；重跑時舊版轉 superseded、只留一個 current。
- `payload_json` 整欄可 NULL：規格鐵律「市場資料是輔助，數值欄必須可空、空值由質性 narrative
  承接」——資料稀薄時只有 narrative、無結構化數值也成立。
- `accepted_at` NULL＝未確認（逐筆確認閘門）。
- 能推導的不另存（沿專案精簡口徑）：不存 is_current 布林（status 已表達）。
"""
from __future__ import annotations

from alembic import op


revision = "0034_market_doc_summary"
down_revision = "0033_company_alias_ai_suggested"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── market_documents：PDF metadata（內容在檔案系統）──────────────
    op.execute(
        """
        CREATE TABLE derived_layer.market_documents (
            document_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id      BIGINT NOT NULL
                REFERENCES app_layer.workspaces(workspace_id) ON DELETE CASCADE,
            original_filename TEXT NOT NULL,
            stored_filename   TEXT NOT NULL,
            file_hash         TEXT NOT NULL,
            byte_size         BIGINT NOT NULL,
            uploaded_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX market_documents_workspace_idx "
        "ON derived_layer.market_documents (workspace_id)"
    )
    op.execute(
        "COMMENT ON TABLE derived_layer.market_documents IS "
        "'市場資料 PDF 的 metadata；內容落檔案系統（MARKET_DOC_ROOT，NAS 佔位），"
        "讀取者為本機 Companion CLI 非 Railway 容器。與存 bytea 的 workspace_documents 落點不同'"
    )
    op.execute(
        "COMMENT ON COLUMN derived_layer.market_documents.stored_filename IS "
        "'落地檔名（相對 MARKET_DOC_ROOT）；列出與刪檔用，避免用原檔名造成衝突或 traversal'"
    )
    op.execute(
        "COMMENT ON COLUMN derived_layer.market_documents.byte_size IS "
        "'檔案大小；內容不在 DB 故須存（無法 length(content) 推導，與 workspace_documents 不同）'"
    )

    # ── market_doc_summaries：AI 摘要版本 ──────────────────────────
    op.execute(
        """
        CREATE TABLE derived_layer.market_doc_summaries (
            summary_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id    BIGINT NOT NULL
                REFERENCES app_layer.workspaces(workspace_id) ON DELETE CASCADE,
            version         INTEGER NOT NULL,
            status          TEXT NOT NULL
                CHECK (status IN ('current', 'superseded')),
            payload_json    JSONB,
            narrative       TEXT,
            source_document TEXT,
            accepted_at     TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    # 查最新現行版是唯一熱路徑（報表／PPT 取用、前端展開）；部分索引只覆蓋 current 列。
    op.execute(
        "CREATE INDEX market_doc_summaries_current_idx "
        "ON derived_layer.market_doc_summaries (workspace_id) WHERE status = 'current'"
    )
    op.execute(
        "COMMENT ON TABLE derived_layer.market_doc_summaries IS "
        "'AI 讀市場 PDF 產出的結構化＋敘述摘要，workspace 級、版本化（重跑產生新版本、"
        "舊版標 superseded）。逐筆確認閘門：accepted_at NULL＝未確認'"
    )
    op.execute(
        "COMMENT ON COLUMN derived_layer.market_doc_summaries.payload_json IS "
        "'結構化數據（統計卡／區域／銷售對象／來源）；⚠ 整欄可 NULL——市場資料是輔助，"
        "數值薄弱時只留質性 narrative，不得為填版硬湊數字'"
    )
    op.execute(
        "COMMENT ON COLUMN derived_layer.market_doc_summaries.status IS "
        "'current／superseded 兩態；重跑時舊版轉 superseded，同一 workspace 只保留一個 current'"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS derived_layer.market_doc_summaries")
    op.execute("DROP TABLE IF EXISTS derived_layer.market_documents")
