"""新增集團層公司正規化治理表與報表 group scope view。

Revision ID: 0050_company_group_normalization
Revises: 0049_sse_event_metadata
Create Date: 2026-08-13
"""
from __future__ import annotations

from alembic import op

revision = "0050_company_group_normalization"
down_revision = "0049_sse_event_metadata"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS derived_layer")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.company_groups (
            group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_name TEXT NOT NULL,
            normalized_group_name TEXT NOT NULL,
            review_status TEXT NOT NULL DEFAULT 'suggested',
            source_type TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_company_groups_review_status
                CHECK (review_status IN ('suggested', 'confirmed', 'rejected')),
            CONSTRAINT ck_company_groups_source_type
                CHECK (source_type IN ('manual', 'cli_ai')),
            CONSTRAINT ck_company_groups_name_nonblank
                CHECK (NULLIF(BTRIM(group_name), '') IS NOT NULL),
            CONSTRAINT ck_company_groups_normalized_name_nonblank
                CHECK (NULLIF(BTRIM(normalized_group_name), '') IS NOT NULL)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.company_group_members (
            member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL
                REFERENCES derived_layer.company_groups(group_id) ON DELETE CASCADE,
            company_code TEXT,
            company_display_name TEXT NOT NULL,
            review_status TEXT NOT NULL DEFAULT 'suggested',
            source_type TEXT NOT NULL,
            evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_company_group_members_review_status
                CHECK (review_status IN ('suggested', 'confirmed', 'rejected')),
            CONSTRAINT ck_company_group_members_source_type
                CHECK (source_type IN ('manual', 'cli_ai')),
            CONSTRAINT ck_company_group_members_display_nonblank
                CHECK (NULLIF(BTRIM(company_display_name), '') IS NOT NULL)
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_company_groups_confirmed_name
        ON derived_layer.company_groups (
            lower(regexp_replace(BTRIM(normalized_group_name), '\\s+', ' ', 'g'))
        )
        WHERE review_status = 'confirmed'
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_company_group_members_confirmed_company
        ON derived_layer.company_group_members (
            lower(regexp_replace(BTRIM(company_display_name), '\\s+', ' ', 'g'))
        )
        WHERE review_status = 'confirmed'
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_company_groups_review_status
        ON derived_layer.company_groups(review_status)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_company_group_members_group_id
        ON derived_layer.company_group_members(group_id)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_company_group_members_review_status
        ON derived_layer.company_group_members(review_status)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_company_group_members_display_lookup
        ON derived_layer.company_group_members (
            lower(regexp_replace(BTRIM(company_display_name), '\\s+', ' ', 'g'))
        )
        """
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW derived_layer.report_patent_base_with_groups AS
        SELECT
            b.*,
            COALESCE(g_app.group_name, b.applicant_display_name) AS applicant_group_display_name,
            COALESCE(g_cur.group_name, b.current_assignee_display_name) AS current_assignee_group_display_name,
            COALESCE(g_recent.group_name, b.recent_assignee_display_name) AS recent_assignee_group_display_name
        FROM derived_layer.report_patent_base b
        LEFT JOIN derived_layer.company_group_members m_app
          ON m_app.review_status = 'confirmed'
         AND lower(regexp_replace(BTRIM(m_app.company_display_name), '\\s+', ' ', 'g'))
             = lower(regexp_replace(BTRIM(b.applicant_display_name), '\\s+', ' ', 'g'))
        LEFT JOIN derived_layer.company_groups g_app
          ON g_app.group_id = m_app.group_id
         AND g_app.review_status = 'confirmed'
        LEFT JOIN derived_layer.company_group_members m_cur
          ON m_cur.review_status = 'confirmed'
         AND lower(regexp_replace(BTRIM(m_cur.company_display_name), '\\s+', ' ', 'g'))
             = lower(regexp_replace(BTRIM(b.current_assignee_display_name), '\\s+', ' ', 'g'))
        LEFT JOIN derived_layer.company_groups g_cur
          ON g_cur.group_id = m_cur.group_id
         AND g_cur.review_status = 'confirmed'
        LEFT JOIN derived_layer.company_group_members m_recent
          ON m_recent.review_status = 'confirmed'
         AND lower(regexp_replace(BTRIM(m_recent.company_display_name), '\\s+', ' ', 'g'))
             = lower(regexp_replace(BTRIM(b.recent_assignee_display_name), '\\s+', ' ', 'g'))
        LEFT JOIN derived_layer.company_groups g_recent
          ON g_recent.group_id = m_recent.group_id
         AND g_recent.review_status = 'confirmed'
        """
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW derived_layer.report_patent_applicant_expanded_with_groups AS
        SELECT
            e.*,
            COALESCE(g_app.group_name, e.applicant_display_name) AS applicant_group_display_name,
            COALESCE(g_recent.group_name, e.recent_assignee_display_name) AS recent_assignee_group_display_name,
            COALESCE(g_recent.group_name, e.recent_assignee_display_name) AS current_assignee_group_display_name
        FROM derived_layer.report_patent_applicant_expanded e
        LEFT JOIN derived_layer.company_group_members m_app
          ON m_app.review_status = 'confirmed'
         AND lower(regexp_replace(BTRIM(m_app.company_display_name), '\\s+', ' ', 'g'))
             = lower(regexp_replace(BTRIM(e.applicant_display_name), '\\s+', ' ', 'g'))
        LEFT JOIN derived_layer.company_groups g_app
          ON g_app.group_id = m_app.group_id
         AND g_app.review_status = 'confirmed'
        LEFT JOIN derived_layer.company_group_members m_recent
          ON m_recent.review_status = 'confirmed'
         AND lower(regexp_replace(BTRIM(m_recent.company_display_name), '\\s+', ' ', 'g'))
             = lower(regexp_replace(BTRIM(e.recent_assignee_display_name), '\\s+', ' ', 'g'))
        LEFT JOIN derived_layer.company_groups g_recent
          ON g_recent.group_id = m_recent.group_id
         AND g_recent.review_status = 'confirmed'
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS derived_layer.report_patent_applicant_expanded_with_groups")
    op.execute("DROP VIEW IF EXISTS derived_layer.report_patent_base_with_groups")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_company_group_members_display_lookup")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_company_group_members_review_status")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_company_group_members_group_id")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_company_groups_review_status")
    op.execute("DROP INDEX IF EXISTS derived_layer.uq_company_group_members_confirmed_company")
    op.execute("DROP INDEX IF EXISTS derived_layer.uq_company_groups_confirmed_name")
    op.execute("DROP TABLE IF EXISTS derived_layer.company_group_members")
    op.execute("DROP TABLE IF EXISTS derived_layer.company_groups")
