"""Add derived patent search terms.

Revision ID: 0051_patent_search_terms
Revises: 0050_company_group_normalization
Create Date: 2026-08-17
"""
from __future__ import annotations

from alembic import op

revision = "0051_patent_search_terms"
down_revision = "0050_company_group_normalization"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE SCHEMA IF NOT EXISTS derived_layer")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS derived_layer.patent_search_terms (
            search_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patent_id BIGINT NOT NULL
                REFERENCES core_layer.patents(id) ON DELETE CASCADE,
            field_key TEXT NOT NULL,
            field_label TEXT NOT NULL,
            term_text TEXT NOT NULL,
            term_lookup TEXT NOT NULL,
            is_primary BOOLEAN NOT NULL DEFAULT false,
            source_rank INTEGER NOT NULL DEFAULT 100,
            refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_patent_search_terms_field_key_nonblank
                CHECK (NULLIF(BTRIM(field_key), '') IS NOT NULL),
            CONSTRAINT ck_patent_search_terms_term_text_nonblank
                CHECK (NULLIF(BTRIM(term_text), '') IS NOT NULL),
            CONSTRAINT ck_patent_search_terms_term_lookup_nonblank
                CHECK (NULLIF(BTRIM(term_lookup), '') IS NOT NULL)
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_patent_search_terms_patent_field_term
        ON derived_layer.patent_search_terms(patent_id, field_key, term_lookup)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_patent_search_terms_patent_id
        ON derived_layer.patent_search_terms(patent_id)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_patent_search_terms_field_lookup
        ON derived_layer.patent_search_terms(field_key, term_lookup)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_patent_search_terms_lookup_trgm
        ON derived_layer.patent_search_terms USING gin (term_lookup gin_trgm_ops)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_patent_search_terms_lookup_trgm")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_patent_search_terms_field_lookup")
    op.execute("DROP INDEX IF EXISTS derived_layer.idx_patent_search_terms_patent_id")
    op.execute("DROP INDEX IF EXISTS derived_layer.uq_patent_search_terms_patent_field_term")
    op.execute("DROP TABLE IF EXISTS derived_layer.patent_search_terms")
